// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.
package getstream

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"testing"
)

func TestVerifyWebhookSignature(t *testing.T) {
	secret := "test-webhook-secret"
	body := []byte(`{"type":"test.event"}`)

	// Compute a valid signature
	h := hmac.New(sha256.New, []byte(secret))
	h.Write(body)
	validSignature := hex.EncodeToString(h.Sum(nil))

	tests := []struct {
		name      string
		body      []byte
		signature string
		secret    string
		want      bool
	}{
		{"valid signature", body, validSignature, secret, true},
		{"wrong signature", body, "invalidsignature", secret, false},
		{"tampered body", []byte(`{"type":"tampered"}`), validSignature, secret, false},
		{"wrong secret", body, validSignature, "wrong-secret", false},
		{"empty signature", body, "", secret, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := VerifyWebhookSignature(tt.body, tt.signature, tt.secret)
			if got != tt.want {
				t.Errorf("VerifyWebhookSignature() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestGetEventType(t *testing.T) {
	tests := []struct {
		name     string
		payload  []byte
		expected string
	}{
		{"valid event type", []byte(`{"type":"message.new"}`), "message.new"},
		{"missing type field", []byte(`{"foo":"bar"}`), ""},
		{"invalid json", []byte(`not json`), ""},
		{"empty object", []byte(`{}`), ""},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := GetEventType(tt.payload)
			if got != tt.expected {
				t.Errorf("GetEventType() = %q, want %q", got, tt.expected)
			}
		})
	}
}

func TestParseWebhookEvent(t *testing.T) {
	tests := []struct {
		name        string
		payload     []byte
		expectType  string
		expectError bool
	}{
		{"parse *", []byte(`{"type":"*"}`), "*", false},
		{"parse appeal.accepted", []byte(`{"type":"appeal.accepted"}`), "appeal.accepted", false},
		{"parse appeal.created", []byte(`{"type":"appeal.created"}`), "appeal.created", false},
		{"parse appeal.rejected", []byte(`{"type":"appeal.rejected"}`), "appeal.rejected", false},
		{"parse call.accepted", []byte(`{"type":"call.accepted"}`), "call.accepted", false},
		{"parse call.blocked_user", []byte(`{"type":"call.blocked_user"}`), "call.blocked_user", false},
		{"parse call.closed_caption", []byte(`{"type":"call.closed_caption"}`), "call.closed_caption", false},
		{"parse call.closed_captions_failed", []byte(`{"type":"call.closed_captions_failed"}`), "call.closed_captions_failed", false},
		{"parse call.closed_captions_started", []byte(`{"type":"call.closed_captions_started"}`), "call.closed_captions_started", false},
		{"parse call.closed_captions_stopped", []byte(`{"type":"call.closed_captions_stopped"}`), "call.closed_captions_stopped", false},
		{"parse call.created", []byte(`{"type":"call.created"}`), "call.created", false},
		{"parse call.deleted", []byte(`{"type":"call.deleted"}`), "call.deleted", false},
		{"parse call.dtmf", []byte(`{"type":"call.dtmf"}`), "call.dtmf", false},
		{"parse call.ended", []byte(`{"type":"call.ended"}`), "call.ended", false},
		{"parse call.frame_recording_failed", []byte(`{"type":"call.frame_recording_failed"}`), "call.frame_recording_failed", false},
		{"parse call.frame_recording_ready", []byte(`{"type":"call.frame_recording_ready"}`), "call.frame_recording_ready", false},
		{"parse call.frame_recording_started", []byte(`{"type":"call.frame_recording_started"}`), "call.frame_recording_started", false},
		{"parse call.frame_recording_stopped", []byte(`{"type":"call.frame_recording_stopped"}`), "call.frame_recording_stopped", false},
		{"parse call.hls_broadcasting_failed", []byte(`{"type":"call.hls_broadcasting_failed"}`), "call.hls_broadcasting_failed", false},
		{"parse call.hls_broadcasting_started", []byte(`{"type":"call.hls_broadcasting_started"}`), "call.hls_broadcasting_started", false},
		{"parse call.hls_broadcasting_stopped", []byte(`{"type":"call.hls_broadcasting_stopped"}`), "call.hls_broadcasting_stopped", false},
		{"parse call.kicked_user", []byte(`{"type":"call.kicked_user"}`), "call.kicked_user", false},
		{"parse call.live_started", []byte(`{"type":"call.live_started"}`), "call.live_started", false},
		{"parse call.member_added", []byte(`{"type":"call.member_added"}`), "call.member_added", false},
		{"parse call.member_removed", []byte(`{"type":"call.member_removed"}`), "call.member_removed", false},
		{"parse call.member_updated", []byte(`{"type":"call.member_updated"}`), "call.member_updated", false},
		{"parse call.member_updated_permission", []byte(`{"type":"call.member_updated_permission"}`), "call.member_updated_permission", false},
		{"parse call.missed", []byte(`{"type":"call.missed"}`), "call.missed", false},
		{"parse call.moderation_blur", []byte(`{"type":"call.moderation_blur"}`), "call.moderation_blur", false},
		{"parse call.moderation_warning", []byte(`{"type":"call.moderation_warning"}`), "call.moderation_warning", false},
		{"parse call.notification", []byte(`{"type":"call.notification"}`), "call.notification", false},
		{"parse call.permission_request", []byte(`{"type":"call.permission_request"}`), "call.permission_request", false},
		{"parse call.permissions_updated", []byte(`{"type":"call.permissions_updated"}`), "call.permissions_updated", false},
		{"parse call.reaction_new", []byte(`{"type":"call.reaction_new"}`), "call.reaction_new", false},
		{"parse call.recording_failed", []byte(`{"type":"call.recording_failed"}`), "call.recording_failed", false},
		{"parse call.recording_ready", []byte(`{"type":"call.recording_ready"}`), "call.recording_ready", false},
		{"parse call.recording_started", []byte(`{"type":"call.recording_started"}`), "call.recording_started", false},
		{"parse call.recording_stopped", []byte(`{"type":"call.recording_stopped"}`), "call.recording_stopped", false},
		{"parse call.rejected", []byte(`{"type":"call.rejected"}`), "call.rejected", false},
		{"parse call.ring", []byte(`{"type":"call.ring"}`), "call.ring", false},
		{"parse call.rtmp_broadcast_failed", []byte(`{"type":"call.rtmp_broadcast_failed"}`), "call.rtmp_broadcast_failed", false},
		{"parse call.rtmp_broadcast_started", []byte(`{"type":"call.rtmp_broadcast_started"}`), "call.rtmp_broadcast_started", false},
		{"parse call.rtmp_broadcast_stopped", []byte(`{"type":"call.rtmp_broadcast_stopped"}`), "call.rtmp_broadcast_stopped", false},
		{"parse call.session_ended", []byte(`{"type":"call.session_ended"}`), "call.session_ended", false},
		{"parse call.session_participant_count_updated", []byte(`{"type":"call.session_participant_count_updated"}`), "call.session_participant_count_updated", false},
		{"parse call.session_participant_joined", []byte(`{"type":"call.session_participant_joined"}`), "call.session_participant_joined", false},
		{"parse call.session_participant_left", []byte(`{"type":"call.session_participant_left"}`), "call.session_participant_left", false},
		{"parse call.session_started", []byte(`{"type":"call.session_started"}`), "call.session_started", false},
		{"parse call.stats_report_ready", []byte(`{"type":"call.stats_report_ready"}`), "call.stats_report_ready", false},
		{"parse call.transcription_failed", []byte(`{"type":"call.transcription_failed"}`), "call.transcription_failed", false},
		{"parse call.transcription_ready", []byte(`{"type":"call.transcription_ready"}`), "call.transcription_ready", false},
		{"parse call.transcription_started", []byte(`{"type":"call.transcription_started"}`), "call.transcription_started", false},
		{"parse call.transcription_stopped", []byte(`{"type":"call.transcription_stopped"}`), "call.transcription_stopped", false},
		{"parse call.unblocked_user", []byte(`{"type":"call.unblocked_user"}`), "call.unblocked_user", false},
		{"parse call.updated", []byte(`{"type":"call.updated"}`), "call.updated", false},
		{"parse call.user_feedback_submitted", []byte(`{"type":"call.user_feedback_submitted"}`), "call.user_feedback_submitted", false},
		{"parse call.user_muted", []byte(`{"type":"call.user_muted"}`), "call.user_muted", false},
		{"parse campaign.completed", []byte(`{"type":"campaign.completed"}`), "campaign.completed", false},
		{"parse campaign.started", []byte(`{"type":"campaign.started"}`), "campaign.started", false},
		{"parse channel.created", []byte(`{"type":"channel.created"}`), "channel.created", false},
		{"parse channel.deleted", []byte(`{"type":"channel.deleted"}`), "channel.deleted", false},
		{"parse channel.frozen", []byte(`{"type":"channel.frozen"}`), "channel.frozen", false},
		{"parse channel.hidden", []byte(`{"type":"channel.hidden"}`), "channel.hidden", false},
		{"parse channel.max_streak_changed", []byte(`{"type":"channel.max_streak_changed"}`), "channel.max_streak_changed", false},
		{"parse channel.muted", []byte(`{"type":"channel.muted"}`), "channel.muted", false},
		{"parse channel.truncated", []byte(`{"type":"channel.truncated"}`), "channel.truncated", false},
		{"parse channel.unfrozen", []byte(`{"type":"channel.unfrozen"}`), "channel.unfrozen", false},
		{"parse channel.unmuted", []byte(`{"type":"channel.unmuted"}`), "channel.unmuted", false},
		{"parse channel.updated", []byte(`{"type":"channel.updated"}`), "channel.updated", false},
		{"parse channel.visible", []byte(`{"type":"channel.visible"}`), "channel.visible", false},
		{"parse channel_batch_update.completed", []byte(`{"type":"channel_batch_update.completed"}`), "channel_batch_update.completed", false},
		{"parse channel_batch_update.started", []byte(`{"type":"channel_batch_update.started"}`), "channel_batch_update.started", false},
		{"parse custom", []byte(`{"type":"custom"}`), "custom", false},
		{"parse export.bulk_image_moderation.error", []byte(`{"type":"export.bulk_image_moderation.error"}`), "export.bulk_image_moderation.error", false},
		{"parse export.bulk_image_moderation.success", []byte(`{"type":"export.bulk_image_moderation.success"}`), "export.bulk_image_moderation.success", false},
		{"parse export.channels.error", []byte(`{"type":"export.channels.error"}`), "export.channels.error", false},
		{"parse export.channels.success", []byte(`{"type":"export.channels.success"}`), "export.channels.success", false},
		{"parse export.moderation_logs.error", []byte(`{"type":"export.moderation_logs.error"}`), "export.moderation_logs.error", false},
		{"parse export.moderation_logs.success", []byte(`{"type":"export.moderation_logs.success"}`), "export.moderation_logs.success", false},
		{"parse export.users.error", []byte(`{"type":"export.users.error"}`), "export.users.error", false},
		{"parse export.users.success", []byte(`{"type":"export.users.success"}`), "export.users.success", false},
		{"parse feeds.activity.added", []byte(`{"type":"feeds.activity.added"}`), "feeds.activity.added", false},
		{"parse feeds.activity.deleted", []byte(`{"type":"feeds.activity.deleted"}`), "feeds.activity.deleted", false},
		{"parse feeds.activity.feedback", []byte(`{"type":"feeds.activity.feedback"}`), "feeds.activity.feedback", false},
		{"parse feeds.activity.marked", []byte(`{"type":"feeds.activity.marked"}`), "feeds.activity.marked", false},
		{"parse feeds.activity.pinned", []byte(`{"type":"feeds.activity.pinned"}`), "feeds.activity.pinned", false},
		{"parse feeds.activity.reaction.added", []byte(`{"type":"feeds.activity.reaction.added"}`), "feeds.activity.reaction.added", false},
		{"parse feeds.activity.reaction.deleted", []byte(`{"type":"feeds.activity.reaction.deleted"}`), "feeds.activity.reaction.deleted", false},
		{"parse feeds.activity.reaction.updated", []byte(`{"type":"feeds.activity.reaction.updated"}`), "feeds.activity.reaction.updated", false},
		{"parse feeds.activity.removed_from_feed", []byte(`{"type":"feeds.activity.removed_from_feed"}`), "feeds.activity.removed_from_feed", false},
		{"parse feeds.activity.restored", []byte(`{"type":"feeds.activity.restored"}`), "feeds.activity.restored", false},
		{"parse feeds.activity.unpinned", []byte(`{"type":"feeds.activity.unpinned"}`), "feeds.activity.unpinned", false},
		{"parse feeds.activity.updated", []byte(`{"type":"feeds.activity.updated"}`), "feeds.activity.updated", false},
		{"parse feeds.bookmark.added", []byte(`{"type":"feeds.bookmark.added"}`), "feeds.bookmark.added", false},
		{"parse feeds.bookmark.deleted", []byte(`{"type":"feeds.bookmark.deleted"}`), "feeds.bookmark.deleted", false},
		{"parse feeds.bookmark.updated", []byte(`{"type":"feeds.bookmark.updated"}`), "feeds.bookmark.updated", false},
		{"parse feeds.bookmark_folder.deleted", []byte(`{"type":"feeds.bookmark_folder.deleted"}`), "feeds.bookmark_folder.deleted", false},
		{"parse feeds.bookmark_folder.updated", []byte(`{"type":"feeds.bookmark_folder.updated"}`), "feeds.bookmark_folder.updated", false},
		{"parse feeds.comment.added", []byte(`{"type":"feeds.comment.added"}`), "feeds.comment.added", false},
		{"parse feeds.comment.deleted", []byte(`{"type":"feeds.comment.deleted"}`), "feeds.comment.deleted", false},
		{"parse feeds.comment.reaction.added", []byte(`{"type":"feeds.comment.reaction.added"}`), "feeds.comment.reaction.added", false},
		{"parse feeds.comment.reaction.deleted", []byte(`{"type":"feeds.comment.reaction.deleted"}`), "feeds.comment.reaction.deleted", false},
		{"parse feeds.comment.reaction.updated", []byte(`{"type":"feeds.comment.reaction.updated"}`), "feeds.comment.reaction.updated", false},
		{"parse feeds.comment.updated", []byte(`{"type":"feeds.comment.updated"}`), "feeds.comment.updated", false},
		{"parse feeds.feed.created", []byte(`{"type":"feeds.feed.created"}`), "feeds.feed.created", false},
		{"parse feeds.feed.deleted", []byte(`{"type":"feeds.feed.deleted"}`), "feeds.feed.deleted", false},
		{"parse feeds.feed.updated", []byte(`{"type":"feeds.feed.updated"}`), "feeds.feed.updated", false},
		{"parse feeds.feed_group.changed", []byte(`{"type":"feeds.feed_group.changed"}`), "feeds.feed_group.changed", false},
		{"parse feeds.feed_group.deleted", []byte(`{"type":"feeds.feed_group.deleted"}`), "feeds.feed_group.deleted", false},
		{"parse feeds.feed_group.restored", []byte(`{"type":"feeds.feed_group.restored"}`), "feeds.feed_group.restored", false},
		{"parse feeds.feed_member.added", []byte(`{"type":"feeds.feed_member.added"}`), "feeds.feed_member.added", false},
		{"parse feeds.feed_member.removed", []byte(`{"type":"feeds.feed_member.removed"}`), "feeds.feed_member.removed", false},
		{"parse feeds.feed_member.updated", []byte(`{"type":"feeds.feed_member.updated"}`), "feeds.feed_member.updated", false},
		{"parse feeds.follow.created", []byte(`{"type":"feeds.follow.created"}`), "feeds.follow.created", false},
		{"parse feeds.follow.deleted", []byte(`{"type":"feeds.follow.deleted"}`), "feeds.follow.deleted", false},
		{"parse feeds.follow.updated", []byte(`{"type":"feeds.follow.updated"}`), "feeds.follow.updated", false},
		{"parse feeds.notification_feed.updated", []byte(`{"type":"feeds.notification_feed.updated"}`), "feeds.notification_feed.updated", false},
		{"parse feeds.stories_feed.updated", []byte(`{"type":"feeds.stories_feed.updated"}`), "feeds.stories_feed.updated", false},
		{"parse flag.updated", []byte(`{"type":"flag.updated"}`), "flag.updated", false},
		{"parse ingress.error", []byte(`{"type":"ingress.error"}`), "ingress.error", false},
		{"parse ingress.started", []byte(`{"type":"ingress.started"}`), "ingress.started", false},
		{"parse ingress.stopped", []byte(`{"type":"ingress.stopped"}`), "ingress.stopped", false},
		{"parse member.added", []byte(`{"type":"member.added"}`), "member.added", false},
		{"parse member.removed", []byte(`{"type":"member.removed"}`), "member.removed", false},
		{"parse member.updated", []byte(`{"type":"member.updated"}`), "member.updated", false},
		{"parse message.deleted", []byte(`{"type":"message.deleted"}`), "message.deleted", false},
		{"parse message.flagged", []byte(`{"type":"message.flagged"}`), "message.flagged", false},
		{"parse message.new", []byte(`{"type":"message.new"}`), "message.new", false},
		{"parse message.pending", []byte(`{"type":"message.pending"}`), "message.pending", false},
		{"parse message.read", []byte(`{"type":"message.read"}`), "message.read", false},
		{"parse message.unblocked", []byte(`{"type":"message.unblocked"}`), "message.unblocked", false},
		{"parse message.undeleted", []byte(`{"type":"message.undeleted"}`), "message.undeleted", false},
		{"parse message.updated", []byte(`{"type":"message.updated"}`), "message.updated", false},
		{"parse moderation.custom_action", []byte(`{"type":"moderation.custom_action"}`), "moderation.custom_action", false},
		{"parse moderation.flagged", []byte(`{"type":"moderation.flagged"}`), "moderation.flagged", false},
		{"parse moderation.mark_reviewed", []byte(`{"type":"moderation.mark_reviewed"}`), "moderation.mark_reviewed", false},
		{"parse moderation_check.completed", []byte(`{"type":"moderation_check.completed"}`), "moderation_check.completed", false},
		{"parse moderation_rule.triggered", []byte(`{"type":"moderation_rule.triggered"}`), "moderation_rule.triggered", false},
		{"parse notification.mark_unread", []byte(`{"type":"notification.mark_unread"}`), "notification.mark_unread", false},
		{"parse notification.reminder_due", []byte(`{"type":"notification.reminder_due"}`), "notification.reminder_due", false},
		{"parse notification.thread_message_new", []byte(`{"type":"notification.thread_message_new"}`), "notification.thread_message_new", false},
		{"parse reaction.deleted", []byte(`{"type":"reaction.deleted"}`), "reaction.deleted", false},
		{"parse reaction.new", []byte(`{"type":"reaction.new"}`), "reaction.new", false},
		{"parse reaction.updated", []byte(`{"type":"reaction.updated"}`), "reaction.updated", false},
		{"parse reminder.created", []byte(`{"type":"reminder.created"}`), "reminder.created", false},
		{"parse reminder.deleted", []byte(`{"type":"reminder.deleted"}`), "reminder.deleted", false},
		{"parse reminder.updated", []byte(`{"type":"reminder.updated"}`), "reminder.updated", false},
		{"parse review_queue_item.new", []byte(`{"type":"review_queue_item.new"}`), "review_queue_item.new", false},
		{"parse review_queue_item.updated", []byte(`{"type":"review_queue_item.updated"}`), "review_queue_item.updated", false},
		{"parse thread.updated", []byte(`{"type":"thread.updated"}`), "thread.updated", false},
		{"parse user.banned", []byte(`{"type":"user.banned"}`), "user.banned", false},
		{"parse user.deactivated", []byte(`{"type":"user.deactivated"}`), "user.deactivated", false},
		{"parse user.deleted", []byte(`{"type":"user.deleted"}`), "user.deleted", false},
		{"parse user.flagged", []byte(`{"type":"user.flagged"}`), "user.flagged", false},
		{"parse user.messages.deleted", []byte(`{"type":"user.messages.deleted"}`), "user.messages.deleted", false},
		{"parse user.muted", []byte(`{"type":"user.muted"}`), "user.muted", false},
		{"parse user.reactivated", []byte(`{"type":"user.reactivated"}`), "user.reactivated", false},
		{"parse user.unbanned", []byte(`{"type":"user.unbanned"}`), "user.unbanned", false},
		{"parse user.unmuted", []byte(`{"type":"user.unmuted"}`), "user.unmuted", false},
		{"parse user.unread_message_reminder", []byte(`{"type":"user.unread_message_reminder"}`), "user.unread_message_reminder", false},
		{"parse user.updated", []byte(`{"type":"user.updated"}`), "user.updated", false},
		{"parse user_group.created", []byte(`{"type":"user_group.created"}`), "user_group.created", false},
		{"parse user_group.deleted", []byte(`{"type":"user_group.deleted"}`), "user_group.deleted", false},
		{"parse user_group.member_added", []byte(`{"type":"user_group.member_added"}`), "user_group.member_added", false},
		{"parse user_group.member_removed", []byte(`{"type":"user_group.member_removed"}`), "user_group.member_removed", false},
		{"parse user_group.updated", []byte(`{"type":"user_group.updated"}`), "user_group.updated", false},
		{"unknown event type", []byte(`{"type":"unknown.event"}`), "", true},
		{"missing type field", []byte(`{"foo":"bar"}`), "", true},
		{"invalid json", []byte(`not json`), "", true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			event, err := ParseWebhookEvent(tt.payload)
			if tt.expectError {
				if err == nil {
					t.Errorf("ParseWebhookEvent() expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("ParseWebhookEvent() unexpected error: %v", err)
			}
			if event.GetEventType() != tt.expectType {
				t.Errorf("event.GetEventType() = %q, want %q", event.GetEventType(), tt.expectType)
			}
		})
	}
}
