name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Release:
    name: 🚀 Release
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v6
        with:
          script: |
            // Getting the release version from the PR source branch
            // Source branch looks like this: release-1.0.0
            const version = context.payload.pull_request.head.ref.split('-')[1]
            core.exportVariable('VERSION', version)

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
